### ISSUE TITLE
Pass through video article attributes

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/n-content-model#26]
We need to pass through `isVideo` and `videoId` to n-section. I was previously bypassing n-content-model which caused issues but it just needs to expect them.

**Comment by andygnewman** [comment]
A thought I had was whether instead of overwriting the item with the output of n-content-model, whether we do an Object.assign, this would then preserve any existing attributes and then only overwrite ones that we want modifying and add any new ones.

**Comment by leggsimon** [comment]
Yep, that seems like a good idea but also seems a little hacky. It would probably be best to just let n-content-model just do everything rather than have this assigned here and that assigned there etc..

**Comment by andygnewman** [comment]
Don't think it is hacky. It just means the responsibility of n-content-model is to provide the data necessary for n-card that isn't provided by the source data directly. Lets discuss later.

**Comment by andygnewman** [comment]
@leggsimon Summary of our conversation then is;

- when Video becomes a type, it need not use n-content-model, as it doesn't require any further decoration to use the Video variant of n-card (all the modelling done here is specific to the article variant of n-card).

So I suggest we can close this issue. [This other issue](https://github.com/Financial-Times/n-content-model/issues/23) deals with retaining non-transformed properties.
