### ISSUE TITLE
Release as a 1.0.0

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/n-content-model#7]
Because semver behaves quite _surprisingly_ below 1.0.0 ( cc @andygnewman )

<img width="745" alt="screen shot 2016-07-05 at 13 18 28" src="https://cloud.githubusercontent.com/assets/825088/16584288/fc0b09a8-42b2-11e6-9c00-6cf8898e8536.png">
http://jubianchi.github.io/semver-check/

**Comment by andygnewman** [comment]
👍

**Comment by matthew-andrews** [comment]
hm, version v1.0.0
